version: "3.8"
services:
  api:
    container_name: expiration-tracker-api-${ENVIRONMENT}
    build:
      dockerfile: ./backend/Dockerfile
      context: ./
    env_file:
      - .env
    volumes:
      - static:/code/static
      - attachments:/code/attachments
    depends_on:
      db:
        condition: service_healthy
    image: expiration-tracker-api-${ENVIRONMENT}
  db:
    image: postgres:alpine3.18
    container_name: expiration-tracker-db-${ENVIRONMENT}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  nginx:
    container_name: expiration-tracker-nginx-${ENVIRONMENT}
    build:
      dockerfile: ./nginx/Dockerfile
      context: ./
      args:
        - PUBLIC_URL
        - API_URL
    restart: always
    ports:
      - 80:80
    env_file:
      - .env
    volumes:
      - static:/static
      - attachments:/attachments
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
volumes:
  static:
  attachments:
  postgres_data:
