# Generated by Django 4.2.5 on 2023-09-19 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "locations",
                "db_table": "locations",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[("GOODS", "Goods"), ("MEDICATIONS", "Medications")], default="GOODS", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("STOCK", "Stock"), ("OPENED", "Opened"), ("DISPOSED", "Disposed"), ("USED", "Used")],
                        default="STOCK",
                        max_length=255,
                    ),
                ),
                ("opening_date", models.DateField(null=True)),
                ("expiration_date", models.DateField(null=True)),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="items.location")),
            ],
            options={
                "verbose_name_plural": "items",
                "db_table": "items",
                "ordering": ("-id",),
            },
        ),
    ]
