# Generated by Django 4.2.5 on 2023-09-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="upc",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["upc"], name="items_upc_6f26a2_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["location"], name="items_locatio_1f2e11_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["status"], name="items_status_bc9bcb_idx"),
        ),
    ]
